### PR TITLE
Use new myst build in pullrequest and push

### PR DESCRIPTION
**Pull request by kmuehlbauer**
A bit more context, what I'm trying to achieve:

## PR

- Use `build-book-pullrequest.yaml` to rebuild the docker container and myst build the book.
- zip the book
- deploy it as preview to GH Pages

## Push to Main

- Use `build-book.yaml` to rebuild the docker container and push it to the registry, myst build the book. 
- zip the book
- deploy it to GH Pages

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
So it looks like the thing is built inside the container, but for some reason the mapping to the outside (GitHub workspace) doesn't work. 

Need to stop now. Moving forward over the weekend hopefully.

**Comment by kmuehlbauer** [comment]
@mgrover1 If at first you don't succeed... It was there right from the beginning. 

I'm not sure why the output https://openradar.github.io/erad2024/_preview/57 looks like it is missing some layout stuff. Maybe because the BASE_URL isn't set and the upload isn't done via the gh pages uploader?

Anyway, that's a good move forward. I'll clean this up and reinstate the removed things over the weekend.

Next steps would be to enable the `build-book` to do the same. Then we should be safe.

**Comment by mgrover1** [comment]
Sounds good! Thanks for all the hard work here @kmuehlbauer 😄

**Comment by kmuehlbauer** [comment]
:heavy_check_mark: Success! Now everything runs smoothly for the PR build. And the website is looking good, too.

I'm going to clean-up now and try to fix the `build-book.yaml` CU run accordingly.

**Comment by kmuehlbauer** [comment]
This is working now as intended. As we can't test the build-book CI run (push) here, let's just test it ;-)

**Pull request merged**
