### PR TITLE
Upload LROSE notebooks

### PR DESCRIPTION
**Pull request by tingyucha**
Three notebooks are uploaded.
1. LROSE basics
2. Multi-Doppler wind retrieval and an overview of the tornado case
3. LROSE wind tutorial

### CODE REVIEW

**Review by mgrover1 — APPROVED** [review]
This looks great to me! Nice work @tingyucha and team 👍

**Comment by tingyucha** [comment]
Thank you Max for your help :) Enjoy the long weekend!


--
Ting-Yu Cha, PhD
Postdoctoral Fellow 
Advanced Study Program
NSF National Center for Atmospheric Research
***@***.*** ***@***.***>

**Comment by mgrover1** [comment]
I can take care of that @kmuehlbauer :)

**Comment by kmuehlbauer** [comment]
Here too!
https://github.com/openradar/erad2024/blob/7336e345bbe194f01d023a8424b0f498d68c2059/.github/workflows/build-book.yaml#L28

And normally before merge, here too:
https://github.com/openradar/erad2024/blob/7336e345bbe194f01d023a8424b0f498d68c2059/.github/workflows/build-book-pullrequest.yaml#L31

**Comment by kmuehlbauer** [comment]
I've pushed a fix so the image can be tagged correct. Fingers crossed!

**Comment by mgrover1** [comment]
> I've pushed a fix so the image can be tagged correct. Fingers crossed!

Thanks 👍 sorry about that!

**Comment by kmuehlbauer** [comment]
No worries. The tagging mechanism is not especially user-friendly. For the CI it might be possible to derive the number from GHA environment, but for the Dockerfile we'll have to make it by hand. So I thought I do not invest much time for that.

**Pull request merged**
