### PR TITLE
Adding pyrad part

### PR DESCRIPTION
**Pull request by wolfidan**
Dear all,

Here is the PR with the content of our pyrad short course. It adds config files, presentations and example outputs.

I added a script to download the data from the S3 bucket that we will need to run before the course.

Thank you,
Daniel

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
One last question, can someone explain why the multitude of png images are necessary to have inside the repo?  As these are in the folder `pyrad_output`, maybe this slipped in by accident and can be removed before merge?

**Comment by wolfidan** [comment]
Hi @kmuehlbauer ,

Sorry for the pyrad_mch that I forgot to remove, I will fix this immediately.
For the pyrad_outputs, I thought I would provide the expected outputs if participants are not able to generate them themselves. But I agree it's a lot of files... :(. Would a tar.gz be ok for you ?

**Comment by kmuehlbauer** [comment]
Yes, @wolfidan a tar.gz would be OK.

Please be aware, that I already added some changes to the PR ( docker tag etc)

**Review by mgrover1 — APPROVED** [review]
Looks great!!

**Comment by kmuehlbauer** [comment]
Thanks all!

**Pull request merged**
