### PR TITLE
ADD: Add intro to open radar science presentation

### LINKED ISSUE #86: Remove duplicate environment.yml file in the repo
I noticed that we have an updated `environment.yml` file in the `/binder` directory and one in the base directory. 
Should we maybe just keep the one in the `/binder` directory so stuffs must be not synchronized every time?

### PR DESCRIPTION
**Pull request by mgrover1**
Add introduction to open radar science presentation and remove old environment file

Closes #86

### CODE REVIEW

**Comment by mgrover1** [comment]
@kmuehlbauer - this migrates the previous presentation to a notebook format... @ghiggi - I will need your feedback on where gpm-api fits into this diagram 👍  we would like to make sure it gets updated!

[image](https://github.com/openradar/erad2024/blob/995c34d17d14f003716b72985fc672cd562d9709/presentations/images/open-radar-tools.png)

**Comment by kmuehlbauer** [comment]
@mgrover1 Will have a closer look later today. Could you please revert the changes on the SVGs? The linter is a bit overaggressive here, I think.

**Comment by kmuehlbauer** [comment]
@mgrover1 @ghiggi I'd sort this to gate-based products because for the matching we use the gate date from GPM and Ground Radar. But it has also outputs on the higher levels.

**Comment by kmuehlbauer** [comment]
@mgrover1 I've taken the chance to add some chances wrt to toc and navigation. This makes the navigation cleaner. Please change/reorder as you see fit.

**Comment by wolfidan** [comment]
oh ok sorry @kmuehlbauer  I was not aware of that. Thank you for checking!

**Comment by ghiggi** [comment]
@mgrover1 I would say from gate-based product to the higher levels ... 
With GPM-API you can also read the raw GPM radar data, process the power spectrum, remove ground/sidelobe clutter and derive the reflectivites, there is a routine to process L1B to L2 products, but I don't know if its worth including it in the "moment correction".

**Comment by kmuehlbauer** [comment]
> this migrates the previous presentation to a notebook format

I like this very much. Is it possible to run as slideshow?

**Comment by mgrover1** [comment]
> @mgrover1 I would say from gate-based product to the higher levels ... With GPM-API you can also read the raw GPM radar data, process the power spectrum, remove ground/sidelobe clutter and derive the reflectivites, there is a routine to process L1B to L2 products, but I don't know if its worth including it in the "moment correction".

Sweet! So everything from:
- Gate-based products
- Compositing
- Radar-based products
- Radar-derived products
- Calibration + monitoring
- Metadata generation

Is there anything excluded from this list?

**Comment by mgrover1** [comment]
> > this migrates the previous presentation to a notebook format
> 
> I like this very much. Is it possible to run as slideshow?

Yes! We can use jupyter reveal to render it as a presentation 😄 https://github.com/cusyio/jupyter-reveal

**Comment by mgrover1** [comment]
@kmuehlbauer - this adds the jupyterlab rise package to the environment, enabling us to render the presentation directly on the hub 👍 
https://github.com/jupyterlab-contrib/rise

I also removed the duplicated environment file and updated the workflows accordingly.

**Review by kmuehlbauer — APPROVED** [review]

**Comment by kmuehlbauer** [comment]
Thanks @mgrover1!

**Pull request merged**
