### PR TITLE
FIX: Fix wradlib hvplot render

### LINKED ISSUE #81: bokeh/hvplot DynamicMap not rendered in output
See https://openradarscience.org/erad2024/wradlib-clutter-beamblockage#use-hvplot-for-zooming-and-panning

Screenshot_20240820_132241_dynamicmap

When run in the pythia-hub everything works fine, though.

### PR DESCRIPTION
**Pull request by mgrover1**
Closes #81 

@kmuehlbauer - For the pages to render properly with myst, I believe the extension needs to be set in the imports section! This adds that in 👍

### CODE REVIEW

**Review by kmuehlbauer — APPROVED** [review]
@mgrover1 Great! Did you run pre-commit,  might need an update, though.

**Comment by mgrover1** [comment]
I did not - I can run it!!

**Comment by mgrover1** [comment]
@kmuehlbauer - this now includes the properly linted notebook

**Comment by kmuehlbauer** [comment]
It seems it didn't help:

https://openradarscience.org/erad2024/_preview/82/wradlib-clutter-beamblockage#use-hvplot-for-zooming-and-panning

**Comment by kmuehlbauer** [comment]
@mgrover1 Do you more ideas to tackle this. Not sure where to ask, though. At least in the past this worked well with the older build system in erad2022.

**Comment by mgrover1** [comment]
I do not... I am curious if we should open an issue on the mystmd side...

**Comment by kmuehlbauer** [comment]
Yes, probably a good idea to ask. Can you suggest where?

So the tricky part is, that the notebook is currently rendered with nbconvert directly via pytest script ( see https://github.com/openradar/erad2024/blob/main/conftest.py).

**Comment by mgrover1** [comment]
New issue opened @kmuehlbauer 😄  https://github.com/jupyter-book/mystmd/issues/1488

**Comment by mgrover1** [comment]
Closing this since I could not resolve this issue

**Pull request closed without merging**
