### PR TITLE
DO NOT MERGE: ADD: Add more robust build deploy workflow

### LINKED ISSUE #50: New myst workflow does not run/render notebooks
Unfortunately, the new workflow does not run the notebooks in CI, at least not in the nightly builds. 

From my perspective it would be better to have rendered output on the page. Otherwise viewers of the page would not see any output, forcing them to run them.

We now see that the new matplotlib 3.9.1 breaking Py-ART, see #49. Would be great to get a fix there in soon.

### PR DESCRIPTION
**Pull request by mgrover1**
Closes #50 

@kmuehlbauer - this runs myst execute which will actually run the notebooks 👍

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@mgrover1 That's great!

To enable building the docker container in pullrequests, I've added `build-book-pullrequest.yaml` in #31. This is the failing CI run in this PR.

We might just fix the current `build-book` and `build-book-pullrequest` with the changes needed for getting the new myst workflow to re-enable the former workflows.

Also you'll need to fix the Py-ART error which surfaced here (get_cmap or something).

**Comment by mgrover1** [comment]
Thanks @kmuehlbauer - I have a fix in for Py-ART 👍 

https://github.com/ARM-DOE/pyart/pull/1614

Waiting for CI to fully pass, then I will merge and release a new version!

**Comment by kmuehlbauer** [comment]
Although this is green, it didn't test the new workflow. I'm working on a general fix, please do not merge!

**Comment by kmuehlbauer** [comment]
@mgrover1 We might have to revisit the approach from #57 and #61 to possibly move myst build from the container back to GH Actions. That we we would not need the additional dependency to nodejs within the container. We would only need to copy the created notebooks from inside the container to outside. We might even get the folder mapping correct to have inside==outside somehow. 

I'm going to close this one now.

**Pull request closed without merging**
