### PR TITLE
ADD: BALTRAD notebooks

### LINKED ISSUE #60: Add BALTRAD shortcourse notebooks to repo
It seems a bit counter-intuitive if we add the BALTRAD notebooks during the docker build process.

I'd suggest to add the notebooks directly to the repo and link them in the TOC.

Let's add them one by one, after #57 is merged.

- [ ] https://github.com/DanielMichelson/baltrad_short_course.git
- [ ] https://github.com/DanielMichelson/baltrad2wradlib.git
- [ ] https://github.com/DanielMichelson/pyart2baltrad.git

### PR DESCRIPTION
**Pull request by kmuehlbauer**
This adds all BALTRAD notebooks.

closes #60

@mgrover1 The data folders are listed below. Maybe establish a folder structure in the bucket like:

```
baltrad 
|-> baltrad_short_course
|-> pyart2baltrad
|-> baltrad2wradlib
```
           
- [x] Baltrad Shortcourse Data https://github.com/DanielMichelson/baltrad_short_course/tree/master/data
- [x] PyART2Baltrad Data https://github.com/DanielMichelson/pyart2baltrad/tree/master/data
- [x] Baltrad2Wradlib Data 1 https://github.com/DanielMichelson/baltrad2wradlib/tree/master/in
- [x] Baltrad2Wradlib Data 2 https://github.com/DanielMichelson/baltrad2wradlib/tree/master/shp

I'll update the notebooks once the data is there.

### CODE REVIEW

**Review by mgrover1 — APPROVED** [review]
I really like the structure here - thanks @kmuehlbauer !

**Comment by mgrover1** [comment]
Unless it makes sense for a follow up PR @kmuehlbauer

**Comment by kmuehlbauer** [comment]
@mgrover1 I can handle it tomorrow, when the data is available. It might also make sense to merge #66 later today.

I have some changes to the toc and folder layout here.

**Comment by mgrover1** [comment]
The datasets have been uploaded as requested @kmuehlbauer 😄 

```bash
pythia/radar/baltrad 
|-> baltrad_short_course
|-> pyart2baltrad
|-> baltrad2wradlib
```

**Comment by kmuehlbauer** [comment]
@mgrover1 This file is missing: https://github.com/DanielMichelson/baltrad_short_course/blob/master/data/2019051509_00_ODIMH5_PVOL6S_VOL_casra.16.h5

**Comment by mgrover1** [comment]
I am checking on this - thanks for raising the issue

**Comment by mgrover1** [comment]
I was missing a recursive copy, the files are there now 👍

**Comment by kmuehlbauer** [comment]
First batch of baltrad_short_course notebooks, pyart and wradlib will come later.

I'm fetching the files to local storage, to not have to change too much in the notebooks.

**Comment by kmuehlbauer** [comment]
I'm going to merge this now. Can't fix the errors locally.

**Pull request merged**
