### PR TITLE
Update GPM-API tutorials

### PR DESCRIPTION
**Pull request by ghiggi**
This PR update the GPM-API introduction tutorial and adds the notebooks for the hands-on session in the afternoon related to SR/GR matching and calibration.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@ghiggi This needs waiting for gpm-api 0.3.1 is on conda-forge.

**Comment by ghiggi** [comment]
@kmuehlbauer yes I know. Waiting for the conda release. The PR will be ready for tomorrow ;)

**Comment by ghiggi** [comment]
Hey @kmuehlbauer. The new release of GPM-API has landed on conda-forge. Do you want to add the docker tags to relaunch the CI and then merge?

**Comment by ghiggi** [comment]
@kmuehlbauer @mgrover1 this can be merged now. I already added the docker PR tag ;)

**Review by kmuehlbauer — APPROVED** [review]

**Pull request merged**
