### PR TITLE
FIX: Ensure latest version of Py-ART is installed

### PR DESCRIPTION
**Pull request by mgrover1**

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
It's a CDN issue https://conda-forge.org/status/

One thing which could work is to download the cobra files using wget and then installing.

**Comment by mgrover1** [comment]
@kmuehlbauer - we know the wheels from pip work... what are your thoughts on moving forward with a pip install until conda-forge issues are resolved?

**Comment by mgrover1** [comment]
I would rather do this than include a manual download of the build?

**Comment by kmuehlbauer** [comment]
Let's see how this works. If you feel confident enough, then I'm good with that, too.

**Comment by mgrover1** [comment]
Let's give it a shot 👍  we can always revert to the previous image

**Pull request merged**
