### PR TITLE
ADD: PyDDA notebook

### PR DESCRIPTION
**Pull request by rcjackson**
This is the first draft of the PyDDA notebook. I'll need to update it again once the datasets in open-radar-data are finalized to fix the paths to the data.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
@rcjackson Thanks Bobby! Please also add an entry to the toc in myst.yml to make the notebook viewable on the page

**Comment by rcjackson** [comment]
> @rcjackson Thanks Bobby! Please also add an entry to the toc in myst.yml to make the notebook viewable on the page

Done!

**Comment by kmuehlbauer** [comment]
Great! Unfortunately we've run into docker rate limit now. I'll follow up with this tomorrow around 6 UTC.

We must have stressed the docker registry too much the last hours : grimacing:.

**Comment by kmuehlbauer** [comment]
@rcjackson This works for most of the time. Only the `to_netcdf` calls break for some reason (malformed attributes). That can be fixed when uploaded.

**Pull request merged**
