### PR TITLE
FIX: PyDDA Wind retrieval notebook and baltrad2wradlib notebook

### PR DESCRIPTION
**Pull request by kmuehlbauer**

### CODE REVIEW

**Comment by mgrover1** [comment]
@kmuehlbauer - can you add the following to the environment file as well? This will help the pydda notebook:
```yaml
  - jaxopt
  - tensorflow>=2.6
  - tensorflow-probability
```

This will likely speed up the execution of the pydda notebooks as well.

**Comment by kmuehlbauer** [comment]
Is this available in conda-forge?

**Comment by mgrover1** [comment]
yep! 👍

**Comment by kmuehlbauer** [comment]
I've had to revert the tensorflow addition. The environment did not resolve. Maybe we need to create two (or more) different environments?

**Pull request merged**
